### PR TITLE
Migrate `ZLibrary` calls to `BdApi` & Change class names

### PR DESCRIPTION
**Pull request by KingGamingYT**
ZeresPluginLibrary is, currently, all but deprecated and its use is not recommended. All main functional parts of the plugin using ZPL have been swapped out for `BdApi`-equivalents for reliability and future-proofing. While I initially planned on it, I did not fully replace ZPL because (1) `BdApi` does not have a changelog system yet for plugins and I didn't want to write my own, and (2) your plugin settings menu seems to be tied into ZPL and I didn't want to mess with it.

Class names have been updated to not include "vc" at the front, as this isn't a Vencord plugin, even if it originates from one.

If I made any mistakes, my apologies! This is my first time contributing to somebody else's plugin. I wish you luck in getting approved!

### CODE REVIEW

**Review by riolubruh — CHANGES_REQUESTED** [review]
Assuming the goal is to remove dependency on ZLibrary altogether:
The plugin uses ZeresPluginLibrary to build itself, and is also used to create the settings menu (as you mentioned), so removing calls to ZeresPluginLibrary doesn't have much of an effect, since the plugin still depends on it in the end. 

Changing the class names doesn't really matter since it's not something that the end user will see or know about, so it makes no difference if you change it or not, and since one of the goals of this project was to match the original implementation pretty closely, it made sense to just leave all the class names as-is.

Overall, if the goal is to remove ZLibrary as a dependency, the remaining references to `Settings` (for building settings UI menus), `Utilities` (used for saving and loading settings), and `ContextMenu` (which is like `BdApi.ContextMenu`, but slightly different) would need to be removed, and then the ZPL "structure" (which is the best way i can describe the rest of the ZPL stuff where the whole plugin is basically wrapped into an object and built with ZPL) would need to just be removed. 

Really the biggest annoyance is the Settings UIs since ZPL makes those really simple to make, and is basically one of its main "selling points", since the alternative is making the UI manually (trading more control over the settings panel for less convenience in the process).

**Comment by zerebos** [comment]
@riolubruh please give me a list of things missing from `BdApi` to migrate away from my library. As King pointed out about that pull request adds in an api for changelog modals as well as a plugin settings builder

**Comment by riolubruh** [comment]
@zerebos The most important ones I think were already mentioned, those being Settings UIs, Utilities with save/load settings with default settings support, and changelogs. Ones that weren't mentioned yet were ZLibrary's `DiscordModules` and `DiscordClassModules`. They are also very helpful for plugin developers since it just makes things simpler, not having to manually fetch those common modules all the time (this is also important because of _performance!_ The less plugins have to get modules themselves, the less times we're grabbing the same modules multiple times. Minimizing the amount of module fetches should always be prioritized since it's a very slow process)
I also personally prefer ZLibrary's syntax for Toasts, it's just simpler to write `Toasts.error` for instance, though obviously that's just a preference; the underlying functionality is in BdApi already, just functions with those names don't.
ZLibrary's Logger is also not in BdApi and it's also got some weird bugs for some reason, that nicer logging should totally be in BdApi already, but for some reason, it's not, and seemingly has to be coded by the plugin developer.
And of course, you might've known it was coming, even though it's deprecated even in ZLibrary, _PluginUpdater_! Sure, the "ideal" method is to get plugins onto the website, but not everybody can (or even wants) to do that (especially with how the submission process is right now). More options for the programmer is better in this case! The functionality in ZLibrary could be improved, though, since for some reason it doesn't compare updates properly once you get into double digit versions by default (ex: 1.2.10 would be considered in need of an update when compared to itself for some reason..?), which is weird since the code of ZLibrary accounts for multi-digit versions in its default versioner and comparator. Not sure what's going on there.

**Comment by zerebos** [comment]
Common modules might be added to the API at some point. Realistically plugins should only grab the modules on initialization so startup performance would be affected by not runtime performance. We reject plugins that repeatedly grab modules without caching or perform searches often at runtiume.

The toast syntactic sugar is something that might be added at some point when we move to a new API structure (e.g. `require("@betterdiscord/toasts")`.

Believe it or not but a logger has never really been requested as part of the API before. I might add it anyways just for completeness but it just wasn't something that seemed wanted by developers.

I hear you about the plugin updater, but that's just not currently in the plans for the API. Unofficial plugins can of course implement their own updaters I guess. The update checker in BetterDiscord does much better with semver comparisons than ZLibrary ever did. But that won't be backported to the library as its deprecated.

**Comment by riolubruh** [comment]
Ended up doing it myself

**Pull request closed without merging**
